services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: license_db
      POSTGRES_USER: license_user
      POSTGRES_PASSWORD: license_pass
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://license_user:license_pass@db:5432/license_db
      - DEBUG=True

volumes:
  postgres_data: