# Generated by Django 5.0.6 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(blank=True, max_length=32)),
                ('ogrnip', models.CharField(blank=True, max_length=32)),
                ('support_hours', models.CharField(blank=True, max_length=120)),
                ('telegram_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('notice_enabled', models.BooleanField(default=False)),
                ('notice_title', models.CharField(blank=True, max_length=160)),
                ('notice_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'настройки сервиса',
                'verbose_name_plural': 'настройки сервиса',
            },
        ),
    ]
