# Generated by Codex on 2026-09-29

from django.db import migrations, models


DEFAULT_CELL_SELECTORS = '\n'.join([
    '[class="_shelfTag_1tkm1_2 ozi-heading-500 _shelfTag_jn3ur_21"]',
    '[data-testid="logItemPlace"]',
])


def migrate_existing_notice(apps, schema_editor):
    ServiceSettings = apps.get_model('licenses', 'ServiceSettings')
    ServiceNotification = apps.get_model('licenses', 'ServiceNotification')
    db_alias = schema_editor.connection.alias

    for settings_obj in ServiceSettings.objects.using(db_alias).all():
        if not settings_obj.notice_text:
            continue
        ServiceNotification.objects.using(db_alias).get_or_create(
            title=settings_obj.notice_title or '',
            text=settings_obj.notice_text,
            defaults={'is_enabled': settings_obj.notice_enabled},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_servicesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesettings',
            name='bank_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='bik',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='cell_selectors',
            field=models.TextField(blank=True, default=DEFAULT_CELL_SELECTORS),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='max_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='service_name',
            field=models.CharField(default='Magic ПВЗ', max_length=120),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ServiceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('text', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'уведомление сервиса',
                'verbose_name_plural': 'уведомления сервиса',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.RunPython(migrate_existing_notice, noop_reverse),
    ]
