# Generated by Codex on 2026-09-29

import re

from django.db import migrations, models


DEFAULT_CELL_CLASS_NAME = '_shelfTag_1tkm1_2 ozi-heading-500 _shelfTag_jn3ur_21'
DEFAULT_CELL_DATA_TESTID = 'logItemPlace'


def extract_attr_selector(selector, attr_name):
    match = re.match(rf'^\[{re.escape(attr_name)}=(["\'])(.*?)\1\]$', selector)
    return match.group(2) if match else ''


def migrate_cell_selector_fields(apps, schema_editor):
    ServiceSettings = apps.get_model('licenses', 'ServiceSettings')
    db_alias = schema_editor.connection.alias

    for settings_obj in ServiceSettings.objects.using(db_alias).all():
        cell_class = settings_obj.cell_number_class or DEFAULT_CELL_CLASS_NAME
        data_testid = settings_obj.cell_number_data_testid or DEFAULT_CELL_DATA_TESTID
        element_id = settings_obj.cell_number_id or ''
        extra_selector = settings_obj.cell_extra_selector or ''

        for raw_selector in (settings_obj.cell_selectors or '').splitlines():
            selector = raw_selector.strip()
            if not selector:
                continue

            parsed_class = extract_attr_selector(selector, 'class')
            if parsed_class:
                cell_class = parsed_class
                continue

            parsed_testid = extract_attr_selector(selector, 'data-testid')
            if parsed_testid:
                data_testid = parsed_testid
                continue

            if selector.startswith('#') and len(selector) > 1:
                element_id = selector[1:]
                continue

            if not extra_selector:
                extra_selector = selector

        settings_obj.cell_number_class = cell_class
        settings_obj.cell_number_data_testid = data_testid
        settings_obj.cell_number_id = element_id
        settings_obj.cell_extra_selector = extra_selector
        settings_obj.save(update_fields=[
            'cell_number_class',
            'cell_number_data_testid',
            'cell_number_id',
            'cell_extra_selector',
        ])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_service_settings_sections_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesettings',
            name='cell_extra_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='cell_number_class',
            field=models.CharField(blank=True, default=DEFAULT_CELL_CLASS_NAME, max_length=255),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='cell_number_data_testid',
            field=models.CharField(blank=True, default=DEFAULT_CELL_DATA_TESTID, max_length=120),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='cell_number_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(migrate_cell_selector_fields, noop_reverse),
    ]
