# Generated by Codex on 2026-09-29

import decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_cell_selector_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesettings',
            name='token_price',
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal('0.00'),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.00'))],
            ),
        ),
    ]
