# Generated by Codex on 2026-09-29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_servicesettings_token_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesettings',
            name='token_price',
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
