# Generated by Django 5.0.6 on 2026-09-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_servicesettings_token_price_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='point_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
