# Generated by Django 5.0.6 on 2026-09-30 03:31

from decimal import Decimal, ROUND_HALF_UP

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_ledger_for_existing_payments(apps, schema_editor):
    BillingAccount = apps.get_model('licenses', 'BillingAccount')
    BillingOperation = apps.get_model('licenses', 'BillingOperation')
    LedgerEntry = apps.get_model('licenses', 'LedgerEntry')
    Payment = apps.get_model('licenses', 'Payment')

    for payment in Payment.objects.filter(status='succeeded').iterator():
        amount_kopecks = int(
            (payment.amount * Decimal('100')).quantize(Decimal('1'), rounding=ROUND_HALF_UP)
        )
        if amount_kopecks <= 0:
            continue

        account, _ = BillingAccount.objects.get_or_create(user_id=payment.user_id)
        operation_type = payment.operation_type or 'token_purchase'
        operation = BillingOperation.objects.create(
            user_id=payment.user_id,
            license_key_id=payment.license_key_id,
            payment_id=payment.id,
            operation_type=operation_type,
            status='succeeded',
            amount_kopecks=amount_kopecks,
            balance_used_kopecks=amount_kopecks,
            external_payment_kopecks=amount_kopecks,
            idempotency_key=f'legacy-payment:{payment.id}',
            description='Исторический платёж до включения внутреннего счёта',
            completed_at=payment.paid_at or payment.created_at,
        )
        balance_after_credit = account.balance_kopecks + amount_kopecks
        LedgerEntry.objects.create(
            account_id=account.id,
            user_id=payment.user_id,
            operation_id=operation.id,
            payment_id=payment.id,
            license_key_id=payment.license_key_id,
            entry_type='external_top_up',
            amount_kopecks=amount_kopecks,
            balance_after_kopecks=balance_after_credit,
            comment='Историческое зачисление оплаты',
        )
        LedgerEntry.objects.create(
            account_id=account.id,
            user_id=payment.user_id,
            operation_id=operation.id,
            payment_id=payment.id,
            license_key_id=payment.license_key_id,
            entry_type=operation_type if operation_type in {'token_purchase', 'token_renewal'} else 'token_purchase',
            amount_kopecks=-amount_kopecks,
            balance_after_kopecks=account.balance_kopecks,
            comment='Историческое списание за токен',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_licensekey_point_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YookassaWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'webhook ЮKassa',
                'verbose_name_plural': 'webhooks ЮKassa',
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='licensekey',
            name='auto_renew_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmation_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='operation_type',
            field=models.CharField(choices=[('top_up', 'Пополнение баланса'), ('token_purchase', 'Покупка токена'), ('token_renewal', 'Продление токена'), ('recurring_top_up', 'Автопополнение баланса'), ('auto_token_renewal', 'Автопродление токена'), ('manual', 'Ручная операция')], default='token_purchase', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='yookassa', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='save_payment_method',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='license_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='licenses.licensekey'),
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_kopecks', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'счёт пользователя',
                'verbose_name_plural': 'счета пользователей',
            },
        ),
        migrations.CreateModel(
            name='BillingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('top_up', 'Пополнение баланса'), ('token_purchase', 'Покупка токена'), ('token_renewal', 'Продление токена'), ('recurring_top_up', 'Автопополнение баланса'), ('auto_token_renewal', 'Автопродление токена'), ('manual', 'Ручная операция')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('succeeded', 'Выполнена'), ('failed', 'Ошибка'), ('canceled', 'Отменена')], default='pending', max_length=20)),
                ('amount_kopecks', models.BigIntegerField(default=0)),
                ('balance_used_kopecks', models.BigIntegerField(default=0)),
                ('external_payment_kopecks', models.BigIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('license_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_operations', to='licenses.licensekey')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_operations', to='licenses.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'операция биллинга',
                'verbose_name_plural': 'операции биллинга',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('external_top_up', 'Пополнение через ЮKassa'), ('recurring_top_up', 'Автопополнение через ЮKassa'), ('manual_credit', 'Ручное зачисление'), ('manual_debit', 'Ручное списание'), ('token_purchase', 'Покупка токена'), ('token_renewal', 'Продление токена'), ('auto_token_renewal', 'Автопродление токена'), ('refund', 'Возврат')], max_length=32)),
                ('amount_kopecks', models.BigIntegerField()),
                ('balance_after_kopecks', models.BigIntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='licenses.billingaccount')),
                ('license_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='licenses.licensekey')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='licenses.billingoperation')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='licenses.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'проводка по счёту',
                'verbose_name_plural': 'проводки по счетам',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='yookassa', max_length=32)),
                ('provider_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('method_type', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сохранённый способ оплаты',
                'verbose_name_plural': 'сохранённые способы оплаты',
                'ordering': ('-is_default', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RecurringTopUpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('amount_kopecks', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_top_up_settings', to=settings.AUTH_USER_MODEL)),
                ('saved_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_top_up_settings', to='licenses.savedpaymentmethod')),
            ],
            options={
                'verbose_name': 'настройки автопополнения',
                'verbose_name_plural': 'настройки автопополнения',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='saved_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='licenses.savedpaymentmethod'),
        ),
        migrations.RunPython(backfill_ledger_for_existing_payments, migrations.RunPython.noop),
    ]
