# Generated by Django 5.0.6 on 2026-10-01 04:23

import django.core.validators
from django.db import migrations, models


def backfill_auto_renew_days(apps, schema_editor):
    LicenseKey = apps.get_model('licenses', 'LicenseKey')
    LicenseKey.objects.filter(
        auto_renew_enabled=True,
        auto_renew_days__isnull=True,
    ).update(auto_renew_days=30)


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_yookassawebhookevent_licensekey_auto_renew_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='auto_renew_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_auto_renew_days, migrations.RunPython.noop),
        migrations.AddField(
            model_name='servicesettings',
            name='token_price_12_months',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='token_price_3_months',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='servicesettings',
            name='token_price_6_months',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicesettings',
            name='token_price',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
